using System.Text;
using SoloSpeaker.Core.PeerLink.Wire;

namespace SoloSpeaker.Core.Tests.WireFormat;

/// <summary>
/// The source definitions the frozen artifact is generated from.
/// </summary>
/// <remarks>
/// <para>
/// This describes <em>which</em> vectors exist and what field values they carry.
/// <c>docs/wire-format.vectors.json</c> holds what the codec produces for them - the
/// canonical bytes and the MACs - and is the thing that freezes. The test compares the two
/// on every run, so the pair cannot drift.
/// </para>
/// <para>
/// Honest bound on what this proves: the artifact was generated by the canonicalizer it
/// freezes, so it cannot catch an error that was present when it was written. What it
/// catches is <em>change</em>.
/// </para>
/// </remarks>
public static class WireVectorDefinitions
{
    private const string ForeignPairIdHex = "00112233445566778899aabbccddeeff";

    private static readonly byte[] ForeignPairKey = [.. Enumerable.Repeat((byte)0xff, 32)];

    /// <summary>Regenerates the whole artifact from the current codec.</summary>
    public static WireVectorFile Build()
    {
        List<RoundTripVector> roundTrip =
        [
            RoundTrip("v1-baseline", "Nominal datagram, micLive false, bye false, mid-range seq",
                WireVectorConstants.Datagram(1, WireVectorConstants.PairIdHex, WireVectorConstants.MachineBHex, 41,
                    WireVectorConstants.MachineBHex, micLive: false, bye: false, WireVectorConstants.BaselineSentUtc)),

            RoundTrip("v1-miclive-true", "Phase 2 shape, proving phase 1 and 2 are wire-compatible",
                WireVectorConstants.Datagram(1, WireVectorConstants.PairIdHex, WireVectorConstants.MachineBHex, 41,
                    WireVectorConstants.MachineBHex, micLive: true, bye: false, WireVectorConstants.BaselineSentUtc)),

            RoundTrip("v1-bye", "The departure datagram",
                WireVectorConstants.Datagram(1, WireVectorConstants.PairIdHex, WireVectorConstants.MachineBHex, 41,
                    WireVectorConstants.MachineBHex, micLive: false, bye: true, WireVectorConstants.BaselineSentUtc)),

            RoundTrip("v1-bye-higher-seq", "bye with seq strictly above the receiver's; activeOwner must not move",
                WireVectorConstants.Datagram(1, WireVectorConstants.PairIdHex, WireVectorConstants.MachineBHex, 9999,
                    WireVectorConstants.MachineBHex, micLive: false, bye: true, WireVectorConstants.BaselineSentUtc)),

            RoundTrip("v1-seq-zero", "seq 0, guarding leading-zero and empty-integer formatting",
                WireVectorConstants.Datagram(1, WireVectorConstants.PairIdHex, WireVectorConstants.MachineBHex, 0,
                    WireVectorConstants.NoneHex, micLive: false, bye: false, WireVectorConstants.BaselineSentUtc)),

            RoundTrip("v1-seq-max", "seq at uint64.Max, guarding 64-bit parse precision",
                WireVectorConstants.Datagram(1, WireVectorConstants.PairIdHex, WireVectorConstants.MachineBHex, ulong.MaxValue,
                    WireVectorConstants.MachineBHex, micLive: false, bye: false, WireVectorConstants.BaselineSentUtc)),

            RoundTrip("v1-owner-is-peer", "activeOwner naming the other roster entry",
                WireVectorConstants.Datagram(1, WireVectorConstants.PairIdHex, WireVectorConstants.MachineBHex, 41,
                    WireVectorConstants.MachineAHex, micLive: false, bye: false, WireVectorConstants.BaselineSentUtc)),

            RoundTrip("v1-owner-unknown", "activeOwner outside the roster; a reducer outcome, not an ingress rejection",
                WireVectorConstants.Datagram(1, WireVectorConstants.PairIdHex, WireVectorConstants.MachineBHex, 41,
                    WireVectorConstants.StrangerHex, micLive: false, bye: false, WireVectorConstants.BaselineSentUtc)),

            RoundTrip("v1-owner-none", "activeOwner is MachineId.None, the pre-claim state of design.md section 5",
                WireVectorConstants.Datagram(1, WireVectorConstants.PairIdHex, WireVectorConstants.MachineBHex, 7,
                    WireVectorConstants.NoneHex, micLive: false, bye: false, WireVectorConstants.BaselineSentUtc)),

            RoundTrip("v1-date-padding", "Single-digit month and day, freezing rule 8 zero-padding",
                WireVectorConstants.Datagram(1, WireVectorConstants.PairIdHex, WireVectorConstants.MachineBHex, 41,
                    WireVectorConstants.MachineBHex, micLive: false, bye: false, "2026-01-05T03:04:05.006Z")),
        ];

        string baseline = roundTrip[0].Datagram;
        string byeDatagram = roundTrip[2].Datagram;

        string foreign = WireVectorConstants.Build(
            WireVectorConstants.Datagram(1, ForeignPairIdHex, WireVectorConstants.MachineBHex, 41,
                WireVectorConstants.MachineBHex, micLive: false, bye: false, WireVectorConstants.BaselineSentUtc),
            ForeignPairKey).Datagram;

        string selfOrigin = WireVectorConstants.Build(
            WireVectorConstants.Datagram(1, WireVectorConstants.PairIdHex, WireVectorConstants.MachineAHex, 41,
                WireVectorConstants.MachineAHex, micLive: false, bye: false, WireVectorConstants.BaselineSentUtc)).Datagram;

        string stranger = WireVectorConstants.Build(
            WireVectorConstants.Datagram(1, WireVectorConstants.PairIdHex, WireVectorConstants.StrangerHex, 1,
                WireVectorConstants.NoneHex, micLive: false, bye: false, WireVectorConstants.BaselineSentUtc)).Datagram;

        string unknownVersion = WireVectorConstants.Build(
            WireVectorConstants.Datagram(2, WireVectorConstants.PairIdHex, WireVectorConstants.MachineBHex, 41,
                WireVectorConstants.MachineBHex, micLive: false, bye: false, WireVectorConstants.BaselineSentUtc)).Datagram;

        static string SignedWithSeq(ulong seq) => WireVectorConstants.Build(
            WireVectorConstants.Datagram(1, WireVectorConstants.PairIdHex, WireVectorConstants.MachineBHex, seq,
                WireVectorConstants.MachineBHex, micLive: false, bye: false, WireVectorConstants.BaselineSentUtc)).Datagram;

        List<IngressVector> ingress =
        [
            Ingress("v1-foreign-pairid", "Another pairing's datagram, signed with another key. Fails steps 1 and 2; must report step 1",
                foreign, rosterPeer: "B", localSeq: 41, pairingWindowOpen: false, "ForeignPairId"),

            Ingress("v1-bad-mac", "One flipped bit in mac",
                FlipLastMacCharacter(baseline), rosterPeer: "B", localSeq: 41, pairingWindowOpen: false, "BadMac"),

            Ingress("v1-missing-miclive", "Field absent: a version mismatch, never inferred as false. Unverifiable, so step 2",
                baseline.Replace(",\"micLive\":false", string.Empty, StringComparison.Ordinal),
                rosterPeer: "B", localSeq: 41, pairingWindowOpen: false, "BadMac"),

            Ingress("v1-missing-bye", "Field absent: a version mismatch, never inferred as false",
                baseline.Replace(",\"bye\":false", string.Empty, StringComparison.Ordinal),
                rosterPeer: "B", localSeq: 41, pairingWindowOpen: false, "BadMac"),

            Ingress("v1-unknown-key", "An extra field, the shape a v2 peer takes. Must pass step 1 and die at step 2 so it is counted",
                InsertBeforeClose(baseline, ",\"extra\":1"),
                rosterPeer: "B", localSeq: 41, pairingWindowOpen: false, "BadMac"),

            Ingress("v1-duplicate-key", "A repeated field; JSON permits it, canonicalization does not",
                InsertBeforeClose(baseline, ",\"seq\":41"),
                rosterPeer: "B", localSeq: 41, pairingWindowOpen: false, "BadMac"),

            Ingress("v1-trailing-bytes", "Rule 4 forbids insignificant whitespace, so a canonical document is consumed exactly",
                baseline + " ", rosterPeer: "B", localSeq: 41, pairingWindowOpen: false, "BadMac"),

            Ingress("v1-self-origin", "Our own heartbeat, heard back off the broadcast. Passes steps 1 and 2 by construction",
                selfOrigin, rosterPeer: "B", localSeq: 41, pairingWindowOpen: false, "SelfOrigin"),

            Ingress("v1-not-in-roster", "Valid mac from a machine outside a complete roster",
                stranger, rosterPeer: "B", localSeq: 41, pairingWindowOpen: false, "NotInRoster"),

            Ingress("v1-pairing-enrollment", "The same datagram with an incomplete roster and the pairing window open",
                stranger, rosterPeer: null, localSeq: 0, pairingWindowOpen: true, "PairingEnrollment"),

            Ingress("v1-pairing-window-closed", "Incomplete roster but the window has expired; both conditions are required",
                stranger, rosterPeer: null, localSeq: 0, pairingWindowOpen: false, "NotInRoster"),

            Ingress("v1-seq-at-bound", "Delta of exactly 1000 is accepted",
                SignedWithSeq(1041), rosterPeer: "B", localSeq: 41, pairingWindowOpen: false, "Accepted"),

            Ingress("v1-seq-over-bound", "Delta of 1001 is dropped and raises error",
                SignedWithSeq(1042), rosterPeer: "B", localSeq: 41, pairingWindowOpen: false, "SeqOutOfBounds"),

            Ingress("v1-seq-max-over-bound", "seq = uint64.Max, which unbounded would pin ownership forever on both machines",
                SignedWithSeq(ulong.MaxValue), rosterPeer: "B", localSeq: 41, pairingWindowOpen: false, "SeqOutOfBounds"),

            Ingress("v1-seq-below-local", "A lower seq, which section 5.4 ignores silently. Guards the unsigned-subtraction wrap",
                SignedWithSeq(5), rosterPeer: "B", localSeq: 41, pairingWindowOpen: false, "Accepted"),

            Ingress("v1-seq-wrap-guard", "localSeq at uint64.Max against seq 0; must not be read as a delta of 1",
                SignedWithSeq(0), rosterPeer: "B", localSeq: ulong.MaxValue, pairingWindowOpen: false, "Accepted"),

            Ingress("v1-unknown-version", "v 2 with every field present and a valid mac - the only shape that reaches step 5",
                unknownVersion, rosterPeer: "B", localSeq: 41, pairingWindowOpen: false, "UnknownVersion"),

            Ingress("v1-bye-bad-mac", "A bye is exempt from section 5.4, never from ingress",
                FlipLastMacCharacter(byeDatagram), rosterPeer: "B", localSeq: 41, pairingWindowOpen: false, "BadMac"),

            Ingress("v1-oversize", "Over the 512-byte bound, rejected before step 1",
                baseline.PadRight(WireProtocol.MaxDatagramBytes + 1),
                rosterPeer: "B", localSeq: 41, pairingWindowOpen: false, "Unreadable"),

            Ingress("v1-not-json", "Not a JSON object; attributable to no numbered step",
                "not a datagram", rosterPeer: "B", localSeq: 41, pairingWindowOpen: false, "Unreadable"),
        ];

        return new WireVectorFile
        {
            Comment =
                "Normative golden vectors for wire format v1. See docs/wire-format.md. " +
                "The pairKey below is a published test constant that authenticates nothing; " +
                "it is not the secret AGENTS.md section 6 protects. Regenerate with " +
                "SOLO_SPEAKER_UPDATE_WIRE_VECTORS=1 and review the diff - a change here is a " +
                "change to a format design.md section 8 freezes in phase 1.",
            TestPairKeyHex = Convert.ToHexStringLower(WireVectorConstants.TestPairKey),
            PairIdHex = WireVectorConstants.PairIdHex,
            MachineAHex = WireVectorConstants.MachineAHex,
            MachineBHex = WireVectorConstants.MachineBHex,
            StrangerHex = WireVectorConstants.StrangerHex,
            RoundTrip = roundTrip,
            Ingress = ingress,
        };
    }

    private static RoundTripVector RoundTrip(string name, string covers, PeerDatagram datagram)
    {
        (string canonical, string full, string mac) = WireVectorConstants.Build(datagram);

        return new RoundTripVector
        {
            Name = name,
            Covers = covers,
            Version = datagram.Version,
            PairId = datagram.PairId.ToString(),
            MachineId = datagram.SenderId.ToString(),
            Seq = datagram.Seq,
            ActiveOwner = datagram.ActiveOwner.ToString(),
            MicLive = datagram.MicLive,
            Bye = datagram.Bye,
            SentUtc = Encoding.UTF8.GetString(TimestampOf(canonical)),
            Canonical = canonical,
            Datagram = full,
            Mac = mac,
        };
    }

    private static IngressVector Ingress(
        string name, string covers, string datagram,
        string? rosterPeer, ulong localSeq, bool pairingWindowOpen, string expected) =>
        new()
        {
            Name = name,
            Covers = covers,
            Datagram = datagram,
            RosterPeer = rosterPeer,
            LocalSeq = localSeq,
            PairingWindowOpen = pairingWindowOpen,
            Expected = expected,
        };

    /// <summary>Extracts the <c>sentUtc</c> value straight out of the canonical text.</summary>
    private static byte[] TimestampOf(string canonical)
    {
        const string marker = "\"sentUtc\":\"";
        int start = canonical.IndexOf(marker, StringComparison.Ordinal) + marker.Length;
        return Encoding.UTF8.GetBytes(canonical.Substring(start, 24));
    }

    private static string FlipLastMacCharacter(string datagram)
    {
        char[] characters = datagram.ToCharArray();
        int position = characters.Length - 3;
        characters[position] = characters[position] == '0' ? '1' : '0';
        return new string(characters);
    }

    private static string InsertBeforeClose(string datagram, string addition) =>
        string.Concat(datagram.AsSpan(0, datagram.Length - 1), addition, "}");
}
