using System.Text;
using SoloSpeaker.Core.Identity;
using SoloSpeaker.Core.PeerLink;
using SoloSpeaker.Core.PeerLink.Wire;

namespace SoloSpeaker.Core.Tests.WireFormat;

/// <summary>
/// The shape of <c>docs/wire-format.vectors.json</c>.
/// </summary>
/// <remarks>
/// Canonical forms are stored as readable UTF-8 strings rather than hex so that a wrong
/// field order or a stray space is visible on review - the whole point of the artifact is
/// that changing it is a deliberate, reviewable act.
/// </remarks>
public sealed record WireVectorFile
{
    public string Comment { get; init; } = string.Empty;

    public string TestPairKeyHex { get; init; } = string.Empty;

    public string PairIdHex { get; init; } = string.Empty;

    public string MachineAHex { get; init; } = string.Empty;

    public string MachineBHex { get; init; } = string.Empty;

    public string StrangerHex { get; init; } = string.Empty;

    public IReadOnlyList<RoundTripVector> RoundTrip { get; init; } = [];

    public IReadOnlyList<IngressVector> Ingress { get; init; } = [];
}

/// <summary>A byte-exact canonical form with its expected MAC, asserted in both directions.</summary>
public sealed record RoundTripVector
{
    public string Name { get; init; } = string.Empty;

    public string Covers { get; init; } = string.Empty;

    public int Version { get; init; }

    public string PairId { get; init; } = string.Empty;

    public string MachineId { get; init; } = string.Empty;

    public ulong Seq { get; init; }

    public string ActiveOwner { get; init; } = string.Empty;

    public bool MicLive { get; init; }

    public bool Bye { get; init; }

    public string SentUtc { get; init; } = string.Empty;

    /// <summary>The canonical form with <c>mac</c> omitted - the bytes the HMAC covers.</summary>
    public string Canonical { get; init; } = string.Empty;

    /// <summary>The full datagram: canonical form plus the <c>mac</c> field.</summary>
    public string Datagram { get; init; } = string.Empty;

    public string Mac { get; init; } = string.Empty;
}

/// <summary>Input bytes plus the context they are judged against, and the expected first failure.</summary>
public sealed record IngressVector
{
    public string Name { get; init; } = string.Empty;

    public string Covers { get; init; } = string.Empty;

    /// <summary>The datagram as UTF-8 text, when it is text at all.</summary>
    public string? Datagram { get; init; }

    /// <summary>The datagram as hex, for inputs that are not valid UTF-8.</summary>
    public string? DatagramHex { get; init; }

    /// <summary>Symbolic roster peer - <c>"B"</c>, or <c>null</c> for an incomplete roster.</summary>
    public string? RosterPeer { get; init; }

    public ulong LocalSeq { get; init; }

    public bool PairingWindowOpen { get; init; }

    public string Expected { get; init; } = string.Empty;

    /// <summary>The raw bytes this vector feeds to the pipeline.</summary>
    public byte[] ToBytes() =>
        DatagramHex is not null
            ? Convert.FromHexString(DatagramHex)
            : Encoding.UTF8.GetBytes(Datagram ?? string.Empty);
}

/// <summary>
/// Shared constants and helpers for the vectors.
/// </summary>
/// <remarks>
/// The <c>pairKey</c> here is a published test constant and is not the secret
/// <c>AGENTS.md</c> §6 protects. That rule covers the 256-bit value generated by §7.7 and
/// held only in <c>config.json</c> on the two real machines; this ramp authenticates
/// nothing, lives only in the test assembly, and <c>docs/wire-format.md</c> anticipates it
/// explicitly.
/// </remarks>
public static class WireVectorConstants
{
    public const string PairIdHex = "b1f0a2c3d4e5f60718293a4b5c6d7e8f";

    /// <summary>Machine A, which the vectors treat as <c>self</c>.</summary>
    public const string MachineAHex = "7f3a9c1e2d4b6a8035179246ab13cd5e";

    /// <summary>Machine B, the peer. Lexicographically the smaller of the two.</summary>
    public const string MachineBHex = "2d81e407fa63b95c18204e7dc6395fa1";

    /// <summary>A machine on neither roster.</summary>
    public const string StrangerHex = "aa00bb11cc22dd33ee44ff5566778899";

    /// <summary>The reserved pre-claim owner of <c>docs/design.md</c> §5.</summary>
    public const string NoneHex = "00000000000000000000000000000000";

    public const string BaselineSentUtc = "2026-09-25T21:07:33.118Z";

    /// <summary>A ramp, so it is self-evidently not real key material.</summary>
    public static byte[] TestPairKey { get; } = [.. Enumerable.Range(0, 32).Select(value => (byte)value)];

    public static PairId PairId => ParsePairId(PairIdHex);

    public static MachineId MachineA => Machine(MachineAHex);

    public static MachineId MachineB => Machine(MachineBHex);

    public static MachineId Stranger => Machine(StrangerHex);

    public static PairId ParsePairId(string hex)
    {
        if (!Core.Identity.PairId.TryParse(hex, out PairId id))
        {
            throw new InvalidOperationException($"Test pair ID '{hex}' is not canonical.");
        }

        return id;
    }

    public static MachineId Machine(string hex)
    {
        if (!MachineId.TryParseOwner(hex, out MachineId id))
        {
            throw new InvalidOperationException($"Test identifier '{hex}' is not canonical.");
        }

        return id;
    }

    /// <summary>The roster machine A holds: itself, plus optionally a peer.</summary>
    public static Roster RosterFor(string? peerSymbol)
    {
        MachineId? peer = peerSymbol switch
        {
            null => null,
            "B" => MachineB,
            _ => throw new InvalidOperationException($"Unknown roster symbol '{peerSymbol}'."),
        };

        if (!Roster.TryCreate(MachineA, peer, out Roster? roster))
        {
            throw new InvalidOperationException("Test roster is invalid.");
        }

        return roster!;
    }

    public static IngressContext Context(string? rosterPeer, ulong localSeq, bool pairingWindowOpen) =>
        IngressContext.ForDatagram(PairId, RosterFor(rosterPeer), localSeq, pairingWindowOpen);

    public static PeerDatagram Datagram(
        int version, string pairIdHex, string machineIdHex, ulong seq,
        string activeOwnerHex, bool micLive, bool bye, string sentUtc) =>
        new(version,
            ParsePairId(pairIdHex),
            Machine(machineIdHex),
            seq,
            Machine(activeOwnerHex),
            micLive,
            bye,
            ParseTimestamp(sentUtc));

    /// <summary>Canonical text, full datagram text, and MAC hex for a set of field values.</summary>
    public static (string Canonical, string Datagram, string Mac) Build(in PeerDatagram datagram) =>
        Build(datagram, TestPairKey);

    /// <summary>The same, under an arbitrary key - used by the step 1 versus step 2 ordering vector.</summary>
    public static (string Canonical, string Datagram, string Mac) Build(in PeerDatagram datagram, ReadOnlySpan<byte> pairKey)
    {
        Span<byte> canonicalBuffer = stackalloc byte[WireProtocol.MaxDatagramBytes];
        int canonicalLength = DatagramCodec.WriteCanonical(datagram, canonicalBuffer);
        string canonical = Encoding.UTF8.GetString(canonicalBuffer[..canonicalLength]);

        Span<byte> fullBuffer = stackalloc byte[WireProtocol.MaxDatagramBytes];
        int fullLength = DatagramCodec.Encode(datagram, pairKey, fullBuffer);
        string full = Encoding.UTF8.GetString(fullBuffer[..fullLength]);

        // The mac is the last field: ...,"mac":"<64 hex>"}
        string mac = full.Substring(full.Length - 2 - WireProtocol.MacHexLength, WireProtocol.MacHexLength);

        return (canonical, full, mac);
    }

    public static DateTimeOffset ParseTimestamp(string text) =>
        DateTimeOffset.ParseExact(
            text,
            "yyyy-MM-ddTHH:mm:ss.fffZ",
            System.Globalization.CultureInfo.InvariantCulture,
            System.Globalization.DateTimeStyles.AssumeUniversal |
            System.Globalization.DateTimeStyles.AdjustToUniversal);
}
